# Generated by Django 4.2.13 on 2024-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img-<built-in function localtime>',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
