# Generated by Django 4.2.13 on 2024-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessShop', '0002_item_img_built_in_function_localtime_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img-<built-in function localtime>',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
