# Generated by Django 4.2.13 on 2024-05-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uselessShop', '0003_alter_item_img_built_in_function_localtime_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img-<built-in function localtime>',
            new_name='img',
        ),
    ]
