# Generated by Django 4.2.13 on 2024-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessShop', '0008_alter_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='media/images/default.png', upload_to='images/'),
        ),
    ]
