# Generated by Django 4.2.13 on 2024-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessShop', '0012_alter_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=30)),
                ('text', models.TextField(blank=True, default='...')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='uselessShop.comment'),
        ),
    ]
